name: Ingest ACP → Update Receipt

on:
  repository_dispatch:
    types: [acp_result]

permissions:
  contents: write

concurrency:
  group: cole-acp-receipt
  cancel-in-progress: false

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decode ACP artifact into docs/
        run: |
          mkdir -p docs
          echo "${{ github.event.client_payload.acp_b64 }}" | base64 -d > docs/acp_result.json
          test -s docs/acp_result.json && jq . docs/acp_result.json

      - name: Merge into receipt.latest.json (commerce.acp)
        run: |
          python - <<'PY'
          from pathlib import Path
          import json, time
          rec = Path("docs/receipt.latest.json")
          acp = Path("docs/acp_result.json")
          j = json.loads(rec.read_text("utf-8")) if rec.exists() else {}
          r = json.loads(acp.read_text("utf-8")) if acp.exists() else {}
          j.setdefault("commerce", {})["acp"] = {
            "flow_id": r.get("flow_id"), "psp": r.get("psp"), "merchant_id": r.get("merchant_id"),
            "token_ref": r.get("token_ref"), "sku": r.get("sku"), "qty": r.get("qty"),
            "subtotal": r.get("subtotal"), "currency": r.get("currency"),
            "status": r.get("status"), "updated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
          }
          Path("docs/receipt.latest.json").write_text(json.dumps(j, indent=2), encoding="utf-8")
          print("[ok] receipt updated with commerce.acp")
          PY

      - name: Commit receipt + artifact
        run: |
          git config user.name  "gh-actions"
          git config user.email "actions@users.noreply.github.com"
          git add docs/receipt.latest.json docs/acp_result.json
          git commit -m "chore(receipt): ingest ACP result" || echo "No changes"
          git push
