# .github/workflows/self_tune.yml
name: self_tune

on:
  workflow_dispatch: {}
  # remove "push" trigger so it doesn't run on every commit

permissions:
  contents: read

jobs:
  tune:
    runs-on: ubuntu-latest
    env:
      # expose secret to the job as ENV (never use secrets.* inside if:)
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Bail out cleanly if no key
        run: |
          if [ -z "$ANTHROPIC_API_KEY" ]; then
            echo "No ANTHROPIC_API_KEY configured; exiting OK."; exit 0
          fi

      - name: Do tuning work
        run: echo "…place tuning steps here…"
